
server.port=8080


spring.datasource.url=jdbc:h2:mem:pulsedeskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


huggingface.api.url=https://api-inference.huggingface.co/models/google/flan-t5-base
huggingface.api.token=YOUR_HF_TOKEN <----